### ISSUE TITLE
[Bug]: Patina SDK v22.2.3 Char8String fail

### ISSUE THREAD

**Issue by yangrongwei** [OpenDevicePartnership/patina#1676]
### Is there an existing issue for this?

- [x] I have searched existing issues

### Current Behavior

My app can build with v22.2.1 but failed on v22.2.3

### Expected Behavior

I do not use Char8String feature, it should pass when I do not use them.

I have locked my patina to "=22.2.1"

@makubacki @joschock

### Steps To Reproduce

error log
```
PS D:\ms_Mabcd\Devices_2\Platform\Raymond\RAY_102\Arrow\Crates\bin> cargo build --target aarch64-unknown-uefi
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   D:\ms_Mabcd\Devices_2\Platform\Raymond\RAY_102\Arrow\Crates\lib\lamina\Cargo.toml
workspace: D:\ms_Mabcd\Devices_2\Platform\Raymond\RAY_102\Arrow\Crates\Cargo.toml
   Compiling patina v22.2.3
error[E0432]: unresolved imports `base::string::Char8String`, `base::string::Char16String`                                                                                                                         
  --> C:\Users\v-rayyang\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\patina-22.2.3\src\lib.rs:26:46
   |
26 | pub use base::string::{Char8Array, Char8Str, Char8String, Char16Array, Char16Str, Char16String, StringError};
   |                                              ^^^^^^^^^^^                          ^^^^^^^^^^^^ no `Char16String` in `base::string`
   |                                              |
   |                                              no `Char8String` in `base::string`
   |
help: a similar name exists in the module
   |
26 - pub use base::string::{Char8Array, Char8Str, Char8String, Char16Array, Char16Str, Char16String, StringError};
26 + pub use base::string::{Char8Array, Char8Str, Char8Str, Char16Array, Char16Str, Char16String, StringError};
   |
help: a similar name exists in the module
   |
26 - pub use base::string::{Char8Array, Char8Str, Char8String, Char16Array, Char16Str, Char16String, StringError};
26 + pub use base::string::{Char8Array, Char8Str, Char8String, Char16Array, Char16Str, Char16Str, StringError};
   |

error[E0432]: unresolved import `char8::Char8String`                                                                                                                                                               
   --> C:\Users\v-rayyang\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\patina-22.2.3\src\base\string.rs:68:39
    |
 68 | pub use char8::{Char8Array, Char8Str, Char8String};
    |                                       ^^^^^^^^^^^ no `Char8String` in `base::string::char8`
    |
    = help: consider importing this unresolved item through its public re-export instead:
            crate::Char8String
note: found an item that was configured out
   --> C:\Users\v-rayyang\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\patina-22.2.3\src\base\string\char8.rs:289:12
    |
287 | #[cfg(any(test, feature = "alloc"))]
    |          ------------------------- the item is gated here
288 | #[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
289 | pub struct Char8String(Vec<u8>);
    |            ^^^^^^^^^^^
help: a similar name exists in the module
    |
 68 - pub use char8::{Char8Array, Char8Str, Char8String};
 68 + pub use char8::{Char8Array, Char8Str, Char8Str};
    |

error[E0432]: unresolved import `char16::Char16String`
   --> C:\Users\v-rayyang\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\patina-22.2.3\src\base\string.rs:69:42
    |
 69 | pub use char16::{Char16Array, Char16Str, Char16String};
    |                                          ^^^^^^^^^^^^ no `Char16String` in `base::string::char16`
    |
    = help: consider importing this unresolved item through its public re-export instead:
            crate::Char16String
note: found an item that was configured out
   --> C:\Users\v-rayyang\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\patina-22.2.3\src\base\string\char16.rs:317:12
    |
315 | #[cfg(any(test, feature = "alloc"))]
    |          ------------------------- the item is gated here
316 | #[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
317 | pub struct Char16String(Vec<u16>);
    |            ^^^^^^^^^^^^
help: a similar name exists in the module
    |
 69 - pub use char16::{Char16Array, Char16Str, Char16String};
 69 + pub use char16::{Char16Array, Char16Str, Char16Str};
    |

For more information about this error, try `rustc --explain E0432`.                                                                                                                                                
error: could not compile `patina` (lib) due to 3 previous errors         
```

### Build Environment

```markdown
- OS(s): Windows 11
- Targets Impacted:
```

### Version Information

```text
Tag: v22.2.3
```

### Urgency

Low

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

Maintainer feedback requested

**Comment by makubacki** [comment]
Hi @yangrongwei, I believe this was already addressed in https://github.com/OpenDevicePartnership/patina/commit/0b2c09a51a00682d61ef13118f0a2ead53e72abc. Can you please try with that commit and report back?

**Comment by yangrongwei** [comment]
Verified, pass. I can build with the commit.

**Comment by makubacki** [comment]
Released in [patina-v22.2.4](https://github.com/OpenDevicePartnership/patina/releases/tag/patina-v22.2.4)
