### ISSUE TITLE
[Bug]: `cargo make patina-test` fails (regression)

### ISSUE THREAD

**Issue by thomashinds** [OpenDevicePartnership/patina#1443]
### Is there an existing issue for this?

- [x] I have searched existing issues

### Current Behavior

`cargo make patina-test` (and therefore `cargo make all` fails with several errors like the following:
```
error[E0433]: failed to resolve: could not find `TEST_CASES` in `__private_api`
  --> components/patina_adv_logger/src/integration_test.rs:21:1
   |
21 | #[patina_test]
   | ^^^^^^^^^^^^^^ could not find `TEST_CASES` in `__private_api`
   |
note: found an item that was configured out
  --> components/patina_test/src/__private_api.rs:28:12
   |
26 | #[cfg(feature = "test-runner")]
   |       ----------------------- the item is gated behind the `test-runner` feature
27 | #[linkme::distributed_slice]
28 | pub static TEST_CASES: [TestCase];
   |            ^^^^^^^^^^
   = note: this error originates in the attribute macro `patina_test` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This regressed in commit https://github.com/OpenDevicePartnership/patina/commit/acb5c1bf0dfb4ab55b40df5cdb9c9e1e50f3ea84, clobbering changes in `Makefile.toml` from https://github.com/OpenDevicePartnership/patina/commit/16fd292a1e4834f5f879020a939c35ba7b578895
(see https://github.com/OpenDevicePartnership/patina/commits/main/Makefile.toml)

### Expected Behavior

`cargo make patina-test` succeeds

### Steps To Reproduce

`cargo make patina-test`

### Build Environment

```markdown
n/a
```

### Version Information

```text
main since https://github.com/OpenDevicePartnership/patina/commit/acb5c1bf0dfb4ab55b40df5cdb9c9e1e50f3ea84
```

### Urgency

Medium

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

[cargo-make-patina-test.txt](https://github.com/user-attachments/files/26362796/cargo-make-patina-test.txt)

**Comment by Javagedes** [comment]
looks like an issue with my change. I will investigate.

**Comment by Javagedes** [comment]
Feature `enable_patina_tests` was replaced with `test-runner` in latest breaking change, requiring an update to the Makefile. I will update patina_devops.

**Comment by Javagedes** [comment]
https://github.com/OpenDevicePartnership/patina-devops/pull/115

**Comment by makubacki** [comment]
> Feature `enable_patina_tests` was replaced with `test-runner` in latest breaking change, requiring an update to the Makefile. I will update patina_devops.

For reference: https://github.com/OpenDevicePartnership/patina/pull/1440
